### PR TITLE
Improved description

### PR DESCRIPTION
**Pull request by tunip**

### CODE REVIEW

**Comment by kiall** [comment]
So, from memory of experimenting with these options and some sample EPG data I was given, this will mean many folks will have no description at all visible within the UI.

I've got some code laying around to add a proper preferences/settings UI, I think we should use that to allow users to pick+choose the option that works for them. I'll push the preferences code up.

**Comment by tunip** [comment]
Thats weird... I use both EPG sources in Tvheadend, DVB OTA (EIT) and XMLTV and description works fine for all events Live Channels. Kodi client is also using only description (not summary).

**Comment by kiall** [comment]
For reference, here is some EPG data for two of my sources, both OTA. One has no subtitle, no summary, and a description. The other has a duplicated subtitle and summary, with no description. For my EPG sources, no description is present on about 80% of episodes. 

    {
      "eventId": 284421,
      "episodeId": 367888,
      "episodeUri": "crid:\/\/rtenl.ie\/226277903",
      "serieslinkId": 369208,
      "serieslinkUri": "crid:\/\/rtenl.ie\/231340113",
      "channelName": "RT\u00c9 One",
      "channelUuid": "a68445e46d8f2a36cf29ba36a1d5c044",
      "channelNumber": "1",
      "channelIcon": "imagecache\/5542",
      "start": 1477665000,
      "stop": 1477667400,
      "title": "Making It Down Under",
      "subtitle": "",
      "summary": "",
      "description": "Series following recent Irish arrivals to Australia. Cork-born flying nurse Alan O'Riordan and his team race to help an elderly woman in danger. (S)",
      "nextEventId": 284423
    },
    {
      "eventId": 330213,
      "episodeId": 330214,
      "serieslinkId": 301568,
      "serieslinkUri": "crid:\/\/onid-2\/0000008752",
      "channelName": "The Vault",
      "channelUuid": "b8ac6be551c2f7a6aa8f6b3c79570613",
      "channelNumber": "501",
      "channelIcon": "imagecache\/5478",
      "start": 1477665000,
      "stop": 1477666800,
      "title": "Saved By The Bell",
      "subtitle": "In order for Kelly to go to a George Michael concert, she has to pass her science test. Zack persuades Screech to tutor Kelly, a ploy which is more for his benefit than for Kelly's. S01 E10",
      "summary": "In order for Kelly to go to a George Michael concert, she has to pass her science test. Zack persuades Screech to tutor Kelly, a ploy which is more for his benefit than for Kelly's. S01 E10",
      "widescreen": 1,
      "nextEventId": 331846
    },

Here's another, this time with a *nearly but not quite* duplicated subtitle and summary:

    {
      "eventId": 324789,
      "episodeId": 316410,
      "episodeUri": "crid:\/\/fp.bbc.co.uk\/2419BO",
      "serieslinkId": 315154,
      "serieslinkUri": "crid:\/\/fp.bbc.co.uk\/O5JLGM",
      "channelName": "BBC One East E",
      "channelUuid": "62b2908a8491e5ca52ca77a9bd7cd810",
      "channelNumber": "953",
      "channelIcon": "imagecache\/5582",
      "start": 1477665900,
      "stop": 1477668600,
      "title": "Money for Nothing",
      "subtitle": "6\/15. Junk makeover show. Sarah saves a petrol can, a rickety dining table and an old chair from being tipped in Witley. [HD] [S]",
      "summary": "6\/15. Junk makeover show. Sarah saves a petrol can, a rickety dining table and an old chair from being tipped in Witley. Also in HD. [S]",
      "widescreen": 1,
      "subtitled": 1,
      "genre": [
        160
      ],
      "nextEventId": 326919
    },

Another with what appears to be very different content in subtitle and summary:

    {
      "eventId": 330972,
      "episodeId": 368511,
      "episodeUri": "crid:\/\/onid-2\/1069372",
      "channelName": "COLORS",
      "channelUuid": "fb3ff194f7ec34351136053ba823b717",
      "channelNumber": "662",
      "channelIcon": "imagecache\/5482",
      "start": 1477666800,
      "stop": 1477668600,
      "title": "Shakti Astitva Ke Ehsaas Ki",
      "subtitle": "Soumya and Surabhi are close-knit sisters. While one is discriminated against by her family and society, the other sister stands up for her through tough times.",
      "summary": "Multiple followers wait at the Ghunghroowali Mata temple to get a glimpse of Maa Kusum Sundari. Gayatri and Basesar visit the temple and leave their young daughter there, by mistake.",
      "nextEventId": 396405
    },

Overall, the consistency of OTA EPG data is just too bad to have any reasonable chance and selecting a single "good" pattern we can always apply.

**Comment by kiall** [comment]
Also for reference, see issue #26

**Comment by tunip** [comment]
I have it. Other question would be if this could be resolved maybe in Tvheadend? You have a very strange OTA EPG (3 different variants).

If I use only OTA EPG in Tvheadend, I always have a description (some events like 3min weather of course do not have one). ~90% of the OTA EPG events have the same Subtitle and Summary 1:1, which looks also weird in Live Channels (duplicate information), because summary is used as description.

Not a trivial issue...

Lets see how it looks with your changes #74  from today. Many thanks!

**Pull request closed without merging**
