### PR TITLE
Add a Default Event Icon so that recommendations work even when your EPG provider does not provide one.

### PR DESCRIPTION
**Pull request by stquinn**
My EPG provider does not provide images for each program.  Because there are no images, I do not get recommnedations.

I have added a default icon for each program, which allows recommendations to work.

The image to use is open to debate..to prove the point I just chose the Apps icon on Google Play Store like attached: 
default_event_icon

Anyway, see what you think. Some variation of this is a nice touch as it gives me the full android tv experience.

### CODE REVIEW

**Comment by kiall** [comment]
I like the idea, but wouldn't use it myself :D I'd get too annoyed by the duplicate images in the EPG. My point here is - lets make this optional :)

Also, we should avoid adding "app specific" code into the HTSP library, we can do something very similar in https://github.com/kiall/android-tvheadend/blob/develop/app/src/main/java/ie/macinnes/tvheadend/sync/EpgSyncTask.java#L216 - after `ContentValues values = message.toContentValues(channelId);` we can do a `if values.getAsString(TvContract.Programs.COLUMN_POSTER_ART_URI) == null, then add default image`. This keeps the app specifics away from the HTSP protocol code..

This can then also be wrapped in a preferences check, to decide if it should be done or not.. The gist of that would be to add the preference into https://github.com/kiall/android-tvheadend/blob/develop/app/src/main/res/xml/preferences.xml#L32 - a matching constant over at https://github.com/kiall/android-tvheadend/blob/develop/app/src/main/java/ie/macinnes/tvheadend/Constants.java#L54 and then check the preference with something like https://github.com/kiall/android-tvheadend/blob/develop/app/src/main/java/ie/macinnes/tvheadend/sync/EpgSyncService.java#L98-L104

**Comment by stquinn** [comment]
Yeah I agree with placement of code. Also I think a more subtle image may help with annoyance factor. 

Even Android TV s default "now playing" icon in the recommendations row when the URL can't be retrieved might be nicer. If I remember correctly it's a dark blue gradient with a white live channels like icon.

**Comment by stquinn** [comment]
As a aside, can I ask what EPG provider you are using for tv in Ireland that provides a thumbnail?

**Comment by kiall** [comment]
I setup WebGrab++ on my TVHeadend box, using the horizon grabber for Saorvoew and TVGuide.co.uk for FreeSAT.

TVHeadend then reads in the xmltv file it generates

**Comment by kiall** [comment]
The bulk of the config I use is at @ https://gist.github.com/kiall/b65b8e1c234bccb4283d40da276ad1c4

**Comment by kiall** [comment]
FYI - Here's a more complete example of how to add a preference for this... https://github.com/kiall/android-tvheadend/pull/112/files

**Comment by stquinn** [comment]
Thanks for the webgrab setup.  I might go back and give it another go.  I had went away from it as it appeared to take forever to do an update but then I was using different providers.

**Comment by kiall** [comment]
It does take forever, but thats OK. Run it twice a day in a crown and let TVHeadend just read in the file it generates :)

Anyway! Enough pull request thread hijacking ;) Move to google + if you have questions on getting it going :)

**Comment by stquinn** [comment]
I have implemented as we discussed.

**Comment by stquinn** [comment]
Just realised that I kind of messed this pull request up with merges. If you were going to accept the final changes then I think it's probably better to close and I will recreate with just one commit rather than litter your commit history.

**Pull request closed without merging**
